
#include <libavutil/avutil.h>
#define ERR(a)         \
  int is_##a(int code) \
  {                    \
    return a == code;  \
  }
ERR(AVERROR_BSF_NOT_FOUND)
ERR(AVERROR_BUG)
ERR(AVERROR_BUFFER_TOO_SMALL)
ERR(AVERROR_DECODER_NOT_FOUND)
ERR(AVERROR_DEMUXER_NOT_FOUND)
ERR(AVERROR_ENCODER_NOT_FOUND)
ERR(AVERROR_EOF)
ERR(AVERROR_EXIT)
ERR(AVERROR_EXTERNAL)
ERR(AVERROR_FILTER_NOT_FOUND)
ERR(AVERROR_INVALIDDATA)
ERR(AVERROR_MUXER_NOT_FOUND)
ERR(AVERROR_OPTION_NOT_FOUND)
ERR(AVERROR_PATCHWELCOME)
ERR(AVERROR_PROTOCOL_NOT_FOUND)
ERR(AVERROR_STREAM_NOT_FOUND)
ERR(AVERROR_BUG2)
ERR(AVERROR_UNKNOWN)
ERR(AVERROR_EXPERIMENTAL)
ERR(AVERROR_INPUT_CHANGED)
ERR(AVERROR_OUTPUT_CHANGED)
ERR(AVERROR_HTTP_BAD_REQUEST)
ERR(AVERROR_HTTP_UNAUTHORIZED)
ERR(AVERROR_HTTP_FORBIDDEN)
ERR(AVERROR_HTTP_NOT_FOUND)
ERR(AVERROR_HTTP_OTHER_4XX)
ERR(AVERROR_HTTP_SERVER_ERROR)
int is_AVERROR_EAGAIN(int code) { return (int)AVERROR(EAGAIN) == code; }
const char *err2str(int errnum)
{
  return av_err2str(errnum);
}